### ISSUE TITLE
Hi Sir!

### ISSUE THREAD

**Issue by Dagdelo** [GandaG/fortune-anti-jokes#1]
I came here to try contact with the creator of Relinker. I don't know if u still have the source code. Since u are out of the scene for your reasons, I humble came here to ask: u can release the source code for those, like me, that want to carry on the good job for the modding community.

**Comment by dh-nunes** [comment]
I always made sure to bundle the source code along with the built binaries. I'm pretty sure hishy has a nexus page with all versions uploaded, just don't judge me too much on the code, it was a quick patch job that got out of control :p

**Comment by Dagdelo** [comment]
Meu inglês é péssimo. Eu não havia notado o source code juntamente com os executáveis. . . Mas de qualquer forma agradeço pela iniciativa de ter criado a ferramenta. Estive conversando com ele no Discord e ele me contou que o problema é com a codificação, a v44 usa utf8...

Enfim vou dá uma olhada no código só por mera curiosidade. Obrigado!
